site_name: AeroWiki

theme: 
  name: material
  language: pt-BR
  palette: 
    primary: dark blue
  font: 
    text: Roboto

nav: 
  - Página inicial: index.md
  - Visão do produto e projeto:
    - Visão geral do produto: visao_do_produto_e_projeto/visao-do-produto.md
    - Visão geral do projeto: visao_do_produto_e_projeto/visao-do-projeto.md
    - Processo de desenvolvimento de software: visao_do_produto_e_projeto/processo-de-desenvolvimento-de-software.md
    - Lições aprendidas: visao_do_produto_e_projeto/licoes-aprendidas.md
